
CREATE DATABASE IF NOT EXISTS kualicoeusdb CHARACTER SET utf8 COLLATE utf8_bin;

GRANT ALL ON `kualicoeusdb`.* TO 'kcusername'@'localhost' IDENTIFIED BY 'kcpassword';

GRANT SELECT ,
INSERT ,
UPDATE ,
DELETE ,
CREATE ,
DROP ,
INDEX ,
ALTER ,
CREATE TEMPORARY TABLES ,
LOCK TABLES ,
CREATE VIEW ,
CREATE ROUTINE,
ALTER ROUTINE ON * . * TO  'kcusername'@'localhost' IDENTIFIED BY  'kcpassword' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

exit
